# For puppetlabs_spec_helper documentation - see https://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
  symlinks:
    nfs/files: '../../../../files'
    nfs/manifests: '../../../../manifests'
    nfs/templates: '../../../../templates'
