---
sudo: false
language: ruby
#bundler_args: --without system_tests
script:
  - rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.5.3"
notifications:
  email: false
