---
sudo: false
language: ruby
bundler_args: --without system_tests
script:
  - bundle exec rspec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
